server:
  port: 8082

spring:
  application:
    name: order-manage
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.186.131:8848

  rabbitmq:
    host: 192.168.186.131
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      direct:
        acknowledge-mode: manual #开启手动ack

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/rabbitmq?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false

mybatis-plus:
    mapper-locations: mapper/*.xml #这个配置是用来连接mapper接口和mapper配置类的
    configuration:
      map-underscore-to-camel-case: true #驼峰转换
    type-aliases-package: com.lq.entity #实体类扫描包